# Opciones generales de HTCondor.
universe = vanilla
#
initialdir = /castle/fperez/pipeline-gatk/001
should_transfer_files = NO
environment = PATH=/castle/fperez//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/plan9/bin
#
# Recursos necesarios para ejecutar el trabajo.
request_cpus = 1
request_memory = 3GB
request_disk = 1GB

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG57.final.ir.rtc.bam
output = results/SM-3MG57.final.ir.rtc.bam.condor_out
log = results/SM-3MG57.final.ir.rtc.bam.condor_log
error = results/SM-3MG57.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5Y.final.ir.rtc.bam
output = results/SM-3MG5Y.final.ir.rtc.bam.condor_out
log = results/SM-3MG5Y.final.ir.rtc.bam.condor_log
error = results/SM-3MG5Y.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3Y.final.ir.rtc.bam
output = results/SM-3MG3Y.final.ir.rtc.bam.condor_out
log = results/SM-3MG3Y.final.ir.rtc.bam.condor_log
error = results/SM-3MG3Y.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4M.final.ir.rtc.bam
output = results/SM-3MG4M.final.ir.rtc.bam.condor_out
log = results/SM-3MG4M.final.ir.rtc.bam.condor_log
error = results/SM-3MG4M.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3O.final.ir.rtc.bam
output = results/SM-3MG3O.final.ir.rtc.bam.condor_out
log = results/SM-3MG3O.final.ir.rtc.bam.condor_log
error = results/SM-3MG3O.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5G.final.ir.rtc.bam
output = results/SM-3MG5G.final.ir.rtc.bam.condor_out
log = results/SM-3MG5G.final.ir.rtc.bam.condor_log
error = results/SM-3MG5G.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG6A.final.ir.rtc.bam
output = results/SM-3MG6A.final.ir.rtc.bam.condor_out
log = results/SM-3MG6A.final.ir.rtc.bam.condor_log
error = results/SM-3MG6A.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPV.final.ir.rtc.bam
output = results/SM-3MGPV.final.ir.rtc.bam.condor_out
log = results/SM-3MGPV.final.ir.rtc.bam.condor_log
error = results/SM-3MGPV.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5C.final.ir.rtc.bam
output = results/SM-3MG5C.final.ir.rtc.bam.condor_out
log = results/SM-3MG5C.final.ir.rtc.bam.condor_log
error = results/SM-3MG5C.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPQ.final.ir.rtc.bam
output = results/SM-3MGPQ.final.ir.rtc.bam.condor_out
log = results/SM-3MGPQ.final.ir.rtc.bam.condor_log
error = results/SM-3MGPQ.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPR.final.ir.rtc.bam
output = results/SM-3MGPR.final.ir.rtc.bam.condor_out
log = results/SM-3MGPR.final.ir.rtc.bam.condor_log
error = results/SM-3MGPR.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5H.final.ir.rtc.bam
output = results/SM-3MG5H.final.ir.rtc.bam.condor_out
log = results/SM-3MG5H.final.ir.rtc.bam.condor_log
error = results/SM-3MG5H.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG45.final.ir.rtc.bam
output = results/SM-3MG45.final.ir.rtc.bam.condor_out
log = results/SM-3MG45.final.ir.rtc.bam.condor_log
error = results/SM-3MG45.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG48.final.ir.rtc.bam
output = results/SM-3MG48.final.ir.rtc.bam.condor_out
log = results/SM-3MG48.final.ir.rtc.bam.condor_log
error = results/SM-3MG48.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5U.final.ir.rtc.bam
output = results/SM-3MG5U.final.ir.rtc.bam.condor_out
log = results/SM-3MG5U.final.ir.rtc.bam.condor_log
error = results/SM-3MG5U.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG65.final.ir.rtc.bam
output = results/SM-3MG65.final.ir.rtc.bam.condor_out
log = results/SM-3MG65.final.ir.rtc.bam.condor_log
error = results/SM-3MG65.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5S.final.ir.rtc.bam
output = results/SM-3MG5S.final.ir.rtc.bam.condor_out
log = results/SM-3MG5S.final.ir.rtc.bam.condor_log
error = results/SM-3MG5S.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4H.final.ir.rtc.bam
output = results/SM-3MG4H.final.ir.rtc.bam.condor_out
log = results/SM-3MG4H.final.ir.rtc.bam.condor_log
error = results/SM-3MG4H.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5F.final.ir.rtc.bam
output = results/SM-3MG5F.final.ir.rtc.bam.condor_out
log = results/SM-3MG5F.final.ir.rtc.bam.condor_log
error = results/SM-3MG5F.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5P.final.ir.rtc.bam
output = results/SM-3MG5P.final.ir.rtc.bam.condor_out
log = results/SM-3MG5P.final.ir.rtc.bam.condor_log
error = results/SM-3MG5P.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3L.final.ir.rtc.bam
output = results/SM-3MG3L.final.ir.rtc.bam.condor_out
log = results/SM-3MG3L.final.ir.rtc.bam.condor_log
error = results/SM-3MG3L.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG67.final.ir.rtc.bam
output = results/SM-3MG67.final.ir.rtc.bam.condor_out
log = results/SM-3MG67.final.ir.rtc.bam.condor_log
error = results/SM-3MG67.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5W.final.ir.rtc.bam
output = results/SM-3MG5W.final.ir.rtc.bam.condor_out
log = results/SM-3MG5W.final.ir.rtc.bam.condor_log
error = results/SM-3MG5W.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4E.final.ir.rtc.bam
output = results/SM-3MG4E.final.ir.rtc.bam.condor_out
log = results/SM-3MG4E.final.ir.rtc.bam.condor_log
error = results/SM-3MG4E.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG66.final.ir.rtc.bam
output = results/SM-3MG66.final.ir.rtc.bam.condor_out
log = results/SM-3MG66.final.ir.rtc.bam.condor_log
error = results/SM-3MG66.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4C.final.ir.rtc.bam
output = results/SM-3MG4C.final.ir.rtc.bam.condor_out
log = results/SM-3MG4C.final.ir.rtc.bam.condor_log
error = results/SM-3MG4C.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPU.final.ir.rtc.bam
output = results/SM-3MGPU.final.ir.rtc.bam.condor_out
log = results/SM-3MGPU.final.ir.rtc.bam.condor_log
error = results/SM-3MGPU.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5V.final.ir.rtc.bam
output = results/SM-3MG5V.final.ir.rtc.bam.condor_out
log = results/SM-3MG5V.final.ir.rtc.bam.condor_log
error = results/SM-3MG5V.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5R.final.ir.rtc.bam
output = results/SM-3MG5R.final.ir.rtc.bam.condor_out
log = results/SM-3MG5R.final.ir.rtc.bam.condor_log
error = results/SM-3MG5R.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPN.final.ir.rtc.bam
output = results/SM-3MGPN.final.ir.rtc.bam.condor_out
log = results/SM-3MGPN.final.ir.rtc.bam.condor_log
error = results/SM-3MGPN.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG55.final.ir.rtc.bam
output = results/SM-3MG55.final.ir.rtc.bam.condor_out
log = results/SM-3MG55.final.ir.rtc.bam.condor_log
error = results/SM-3MG55.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3Z.final.ir.rtc.bam
output = results/SM-3MG3Z.final.ir.rtc.bam.condor_out
log = results/SM-3MG3Z.final.ir.rtc.bam.condor_log
error = results/SM-3MG3Z.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5N.final.ir.rtc.bam
output = results/SM-3MG5N.final.ir.rtc.bam.condor_out
log = results/SM-3MG5N.final.ir.rtc.bam.condor_log
error = results/SM-3MG5N.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4N.final.ir.rtc.bam
output = results/SM-3MG4N.final.ir.rtc.bam.condor_out
log = results/SM-3MG4N.final.ir.rtc.bam.condor_log
error = results/SM-3MG4N.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG56.final.ir.rtc.bam
output = results/SM-3MG56.final.ir.rtc.bam.condor_out
log = results/SM-3MG56.final.ir.rtc.bam.condor_log
error = results/SM-3MG56.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPZ.final.ir.rtc.bam
output = results/SM-3MGPZ.final.ir.rtc.bam.condor_out
log = results/SM-3MGPZ.final.ir.rtc.bam.condor_log
error = results/SM-3MGPZ.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG6B.final.ir.rtc.bam
output = results/SM-3MG6B.final.ir.rtc.bam.condor_out
log = results/SM-3MG6B.final.ir.rtc.bam.condor_log
error = results/SM-3MG6B.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5D.final.ir.rtc.bam
output = results/SM-3MG5D.final.ir.rtc.bam.condor_out
log = results/SM-3MG5D.final.ir.rtc.bam.condor_log
error = results/SM-3MG5D.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5L.final.ir.rtc.bam
output = results/SM-3MG5L.final.ir.rtc.bam.condor_out
log = results/SM-3MG5L.final.ir.rtc.bam.condor_log
error = results/SM-3MG5L.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5T.final.ir.rtc.bam
output = results/SM-3MG5T.final.ir.rtc.bam.condor_out
log = results/SM-3MG5T.final.ir.rtc.bam.condor_log
error = results/SM-3MG5T.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4P.final.ir.rtc.bam
output = results/SM-3MG4P.final.ir.rtc.bam.condor_out
log = results/SM-3MG4P.final.ir.rtc.bam.condor_log
error = results/SM-3MG4P.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5M.final.ir.rtc.bam
output = results/SM-3MG5M.final.ir.rtc.bam.condor_out
log = results/SM-3MG5M.final.ir.rtc.bam.condor_log
error = results/SM-3MG5M.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5E.final.ir.rtc.bam
output = results/SM-3MG5E.final.ir.rtc.bam.condor_out
log = results/SM-3MG5E.final.ir.rtc.bam.condor_log
error = results/SM-3MG5E.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4D.final.ir.rtc.bam
output = results/SM-3MG4D.final.ir.rtc.bam.condor_out
log = results/SM-3MG4D.final.ir.rtc.bam.condor_log
error = results/SM-3MG4D.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5J.final.ir.rtc.bam
output = results/SM-3MG5J.final.ir.rtc.bam.condor_out
log = results/SM-3MG5J.final.ir.rtc.bam.condor_log
error = results/SM-3MG5J.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4W.final.ir.rtc.bam
output = results/SM-3MG4W.final.ir.rtc.bam.condor_out
log = results/SM-3MG4W.final.ir.rtc.bam.condor_log
error = results/SM-3MG4W.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3M.final.ir.rtc.bam
output = results/SM-3MG3M.final.ir.rtc.bam.condor_out
log = results/SM-3MG3M.final.ir.rtc.bam.condor_log
error = results/SM-3MG3M.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3V.final.ir.rtc.bam
output = results/SM-3MG3V.final.ir.rtc.bam.condor_out
log = results/SM-3MG3V.final.ir.rtc.bam.condor_log
error = results/SM-3MG3V.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4S.final.ir.rtc.bam
output = results/SM-3MG4S.final.ir.rtc.bam.condor_out
log = results/SM-3MG4S.final.ir.rtc.bam.condor_log
error = results/SM-3MG4S.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4K.final.ir.rtc.bam
output = results/SM-3MG4K.final.ir.rtc.bam.condor_out
log = results/SM-3MG4K.final.ir.rtc.bam.condor_log
error = results/SM-3MG4K.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4F.final.ir.rtc.bam
output = results/SM-3MG4F.final.ir.rtc.bam.condor_out
log = results/SM-3MG4F.final.ir.rtc.bam.condor_log
error = results/SM-3MG4F.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPP.final.ir.rtc.bam
output = results/SM-3MGPP.final.ir.rtc.bam.condor_out
log = results/SM-3MGPP.final.ir.rtc.bam.condor_log
error = results/SM-3MGPP.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG62.final.ir.rtc.bam
output = results/SM-3MG62.final.ir.rtc.bam.condor_out
log = results/SM-3MG62.final.ir.rtc.bam.condor_log
error = results/SM-3MG62.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4Q.final.ir.rtc.bam
output = results/SM-3MG4Q.final.ir.rtc.bam.condor_out
log = results/SM-3MG4Q.final.ir.rtc.bam.condor_log
error = results/SM-3MG4Q.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4G.final.ir.rtc.bam
output = results/SM-3MG4G.final.ir.rtc.bam.condor_out
log = results/SM-3MG4G.final.ir.rtc.bam.condor_log
error = results/SM-3MG4G.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG51.final.ir.rtc.bam
output = results/SM-3MG51.final.ir.rtc.bam.condor_out
log = results/SM-3MG51.final.ir.rtc.bam.condor_log
error = results/SM-3MG51.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPL.final.ir.rtc.bam
output = results/SM-3MGPL.final.ir.rtc.bam.condor_out
log = results/SM-3MGPL.final.ir.rtc.bam.condor_log
error = results/SM-3MGPL.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPX.final.ir.rtc.bam
output = results/SM-3MGPX.final.ir.rtc.bam.condor_out
log = results/SM-3MGPX.final.ir.rtc.bam.condor_log
error = results/SM-3MGPX.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3R.final.ir.rtc.bam
output = results/SM-3MG3R.final.ir.rtc.bam.condor_out
log = results/SM-3MG3R.final.ir.rtc.bam.condor_log
error = results/SM-3MG3R.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4R.final.ir.rtc.bam
output = results/SM-3MG4R.final.ir.rtc.bam.condor_out
log = results/SM-3MG4R.final.ir.rtc.bam.condor_log
error = results/SM-3MG4R.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPY.final.ir.rtc.bam
output = results/SM-3MGPY.final.ir.rtc.bam.condor_out
log = results/SM-3MGPY.final.ir.rtc.bam.condor_log
error = results/SM-3MGPY.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG47.final.ir.rtc.bam
output = results/SM-3MG47.final.ir.rtc.bam.condor_out
log = results/SM-3MG47.final.ir.rtc.bam.condor_log
error = results/SM-3MG47.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4A.final.ir.rtc.bam
output = results/SM-3MG4A.final.ir.rtc.bam.condor_out
log = results/SM-3MG4A.final.ir.rtc.bam.condor_log
error = results/SM-3MG4A.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4Y.final.ir.rtc.bam
output = results/SM-3MG4Y.final.ir.rtc.bam.condor_out
log = results/SM-3MG4Y.final.ir.rtc.bam.condor_log
error = results/SM-3MG4Y.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG59.final.ir.rtc.bam
output = results/SM-3MG59.final.ir.rtc.bam.condor_out
log = results/SM-3MG59.final.ir.rtc.bam.condor_log
error = results/SM-3MG59.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5A.final.ir.rtc.bam
output = results/SM-3MG5A.final.ir.rtc.bam.condor_out
log = results/SM-3MG5A.final.ir.rtc.bam.condor_log
error = results/SM-3MG5A.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4B.final.ir.rtc.bam
output = results/SM-3MG4B.final.ir.rtc.bam.condor_out
log = results/SM-3MG4B.final.ir.rtc.bam.condor_log
error = results/SM-3MG4B.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG64.final.ir.rtc.bam
output = results/SM-3MG64.final.ir.rtc.bam.condor_out
log = results/SM-3MG64.final.ir.rtc.bam.condor_log
error = results/SM-3MG64.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPS.final.ir.rtc.bam
output = results/SM-3MGPS.final.ir.rtc.bam.condor_out
log = results/SM-3MGPS.final.ir.rtc.bam.condor_log
error = results/SM-3MGPS.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG46.final.ir.rtc.bam
output = results/SM-3MG46.final.ir.rtc.bam.condor_out
log = results/SM-3MG46.final.ir.rtc.bam.condor_log
error = results/SM-3MG46.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4T.final.ir.rtc.bam
output = results/SM-3MG4T.final.ir.rtc.bam.condor_out
log = results/SM-3MG4T.final.ir.rtc.bam.condor_log
error = results/SM-3MG4T.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4J.final.ir.rtc.bam
output = results/SM-3MG4J.final.ir.rtc.bam.condor_out
log = results/SM-3MG4J.final.ir.rtc.bam.condor_log
error = results/SM-3MG4J.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4X.final.ir.rtc.bam
output = results/SM-3MG4X.final.ir.rtc.bam.condor_out
log = results/SM-3MG4X.final.ir.rtc.bam.condor_log
error = results/SM-3MG4X.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG63.final.ir.rtc.bam
output = results/SM-3MG63.final.ir.rtc.bam.condor_out
log = results/SM-3MG63.final.ir.rtc.bam.condor_log
error = results/SM-3MG63.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG69.final.ir.rtc.bam
output = results/SM-3MG69.final.ir.rtc.bam.condor_out
log = results/SM-3MG69.final.ir.rtc.bam.condor_log
error = results/SM-3MG69.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5B.final.ir.rtc.bam
output = results/SM-3MG5B.final.ir.rtc.bam.condor_out
log = results/SM-3MG5B.final.ir.rtc.bam.condor_log
error = results/SM-3MG5B.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5Q.final.ir.rtc.bam
output = results/SM-3MG5Q.final.ir.rtc.bam.condor_out
log = results/SM-3MG5Q.final.ir.rtc.bam.condor_log
error = results/SM-3MG5Q.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG49.final.ir.rtc.bam
output = results/SM-3MG49.final.ir.rtc.bam.condor_out
log = results/SM-3MG49.final.ir.rtc.bam.condor_log
error = results/SM-3MG49.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG58.final.ir.rtc.bam
output = results/SM-3MG58.final.ir.rtc.bam.condor_out
log = results/SM-3MG58.final.ir.rtc.bam.condor_log
error = results/SM-3MG58.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4O.final.ir.rtc.bam
output = results/SM-3MG4O.final.ir.rtc.bam.condor_out
log = results/SM-3MG4O.final.ir.rtc.bam.condor_log
error = results/SM-3MG4O.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPO.final.ir.rtc.bam
output = results/SM-3MGPO.final.ir.rtc.bam.condor_out
log = results/SM-3MGPO.final.ir.rtc.bam.condor_log
error = results/SM-3MGPO.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4V.final.ir.rtc.bam
output = results/SM-3MG4V.final.ir.rtc.bam.condor_out
log = results/SM-3MG4V.final.ir.rtc.bam.condor_log
error = results/SM-3MG4V.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3P.final.ir.rtc.bam
output = results/SM-3MG3P.final.ir.rtc.bam.condor_out
log = results/SM-3MG3P.final.ir.rtc.bam.condor_log
error = results/SM-3MG3P.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3U.final.ir.rtc.bam
output = results/SM-3MG3U.final.ir.rtc.bam.condor_out
log = results/SM-3MG3U.final.ir.rtc.bam.condor_log
error = results/SM-3MG3U.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4L.final.ir.rtc.bam
output = results/SM-3MG4L.final.ir.rtc.bam.condor_out
log = results/SM-3MG4L.final.ir.rtc.bam.condor_log
error = results/SM-3MG4L.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG53.final.ir.rtc.bam
output = results/SM-3MG53.final.ir.rtc.bam.condor_out
log = results/SM-3MG53.final.ir.rtc.bam.condor_log
error = results/SM-3MG53.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG68.final.ir.rtc.bam
output = results/SM-3MG68.final.ir.rtc.bam.condor_out
log = results/SM-3MG68.final.ir.rtc.bam.condor_log
error = results/SM-3MG68.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG3N.final.ir.rtc.bam
output = results/SM-3MG3N.final.ir.rtc.bam.condor_out
log = results/SM-3MG3N.final.ir.rtc.bam.condor_log
error = results/SM-3MG3N.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5Z.final.ir.rtc.bam
output = results/SM-3MG5Z.final.ir.rtc.bam.condor_out
log = results/SM-3MG5Z.final.ir.rtc.bam.condor_log
error = results/SM-3MG5Z.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG52.final.ir.rtc.bam
output = results/SM-3MG52.final.ir.rtc.bam.condor_out
log = results/SM-3MG52.final.ir.rtc.bam.condor_log
error = results/SM-3MG52.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MGPW.final.ir.rtc.bam
output = results/SM-3MGPW.final.ir.rtc.bam.condor_out
log = results/SM-3MGPW.final.ir.rtc.bam.condor_log
error = results/SM-3MGPW.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG61.final.ir.rtc.bam
output = results/SM-3MG61.final.ir.rtc.bam.condor_out
log = results/SM-3MG61.final.ir.rtc.bam.condor_log
error = results/SM-3MG61.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG4U.final.ir.rtc.bam
output = results/SM-3MG4U.final.ir.rtc.bam.condor_out
log = results/SM-3MG4U.final.ir.rtc.bam.condor_log
error = results/SM-3MG4U.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG5O.final.ir.rtc.bam
output = results/SM-3MG5O.final.ir.rtc.bam.condor_out
log = results/SM-3MG5O.final.ir.rtc.bam.condor_log
error = results/SM-3MG5O.final.ir.rtc.bam.condor_err
queue

executable = /usr/bin/time
arguments = /usr/lib/plan9/bin/mk results/SM-3MG54.final.ir.rtc.bam
output = results/SM-3MG54.final.ir.rtc.bam.condor_out
log = results/SM-3MG54.final.ir.rtc.bam.condor_log
error = results/SM-3MG54.final.ir.rtc.bam.condor_err
queue
