< ../config.mk

results/%.recal-tab1:	data/%.markdup.ir.rtc.bam 
	set -x
	mkdir -p `dirname $target`
	java -jar $GATK \
		-T BaseRecalibrator \
		-R $REF \
		-I "data/"$stem".markdup.ir.rtc.bam" \
		-knownSites $INDELs \
		-knownSites $dbSNP \
		-nct $NT \
		-o $target".build" \
	&& mv $target".build" $target 


results/%.recal1.bam: data/%.markdup.ir.rtc.bam results/%.recal-tab1 
	set -x
	java -jar $GATK \
		-T PrintReads \
		-R $REF \
		-I "data/"$stem".markdup.ir.rtc.bam" \
		-o $target".build" \
                -BQSR "results/"$stem".recal-tab1" \
		-nct $NT \
	&& mv $target".build" $target \
        && mv $target".build.bai" $target".bai"


results/%.recal-tab2:        results/%.recal1.bam 
        set -x
        java -jar $GATK \
		-T BaseRecalibrator \
		-R $REF \
		-I "results/"$stem".recal1.bam" \
		-knownSites $INDELs \
		-knownSites $dbSNP \
		-nct $NT \
		-o $target".build" \
        && mv $target".build" $target

results/%.BQSR_plot.pdf:  results/%.recal-tab2 results/%.recal-tab1
 set -x
 java -jar $GATK \
      -T AnalyzeCovariates \
      -l DEBUG \
      -R $REF \
      -before "results/"$stem".recal-tab1" \
      -after "results/"$stem".recal-tab2" \
      -csv "results/"$stem".BQSR_plot.csv.build" \
      -plots $target".build" \
      && mv $target".build" $target \
      && mv "results/"$stem".BQSR_plot.csv.build" "results/"$stem".BQSR_plot.csv"


results/%.recal2.bam: results/%.recal1.bam results/%.recal-tab2  results/%.BQSR_plot.pdf
        set -x
	mkdir -p `dirname $target`
        java -jar $GATK \
                -T PrintReads \
                -R $REF \
                -I "results/"$stem".recal1.bam" \
                -o $target".build" \
                -nct $NT \
                -BQSR "results/"$stem".recal-tab2" \
        && mv $target".build" $target \
        && mv $target".build.bai" $target".bai" \
        && rm "results/"$stem".recal1.bam" \
	&& rm "results/"$stem".recal1.bam.bai" \
        && rm "data/"$stem".markdup.ir.rtc.bam" \
	&& rm "data/"$stem".markdup.ir.rtc.bam.bai" \
        && rm "data/"$stem".markdup.intervals"

