<config.mk

prueba1:VE:
	./bin/targets | xargs mk

results/%.recal-tab1:E:	data/%.final.ir.rtc.bam coord.bed
	set -x
	java -jar $GATK \
	-T BaseRecalibrator \
        -R $REF \
        -L coord.bed \
	-I "data/"$stem".final.ir.rtc.bam" \
        -knownSites $VARIANTS \
        -nct $NT \
        -o $target".build" \
  	&& mv $target".build" $target 


results/%.recal1.bam:E: data/%.final.ir.rtc.bam results/%.recal-tab1 coord.bed
	set -x
	java -jar $GATK \
		-T PrintReads \
		-R $REF \
		-L coord.bed \
		-I "data/"$stem".final.ir.rtc.bam" \
		-o $target".build" \
                -BQSR "results/"$stem".recal-tab1" \
		-nct $NT \
	&& mv $target".build" $target \
        && mv $target".build.bai" $target".bai"


results/%.recal-tab2:E:        results/%.recal1.bam coord.bed
        set -x
        java -jar $GATK \
        -T BaseRecalibrator \
        -R $REF \
        -L coord.bed \
        -I "results/"$stem".recal1.bam" \
        -knownSites $VARIANTS \
        -nct $NT \
        -o $target".build" \
        && mv $target".build" $target


results/%.recal2.bam:E: results/%.recal1.bam results/%.recal-tab2 coord.bed
        set -x
	mkdir -p `dirname $target`
        java -jar $GATK \
                -T PrintReads \
                -R $REF \
                -L coord.bed \
                -I "results/"$stem".recal1.bam" \
                -o $target".build" \
                -nct $NT \
                -BQSR "results/"$stem".recal-tab2" \
        && mv $target".build" $target \
        && mv $target".build.bai" $target".bai"

