< ../config.mk

results/Llamado-conjunto_raw.vcf:
        set -x
        datos=`{find -L data/ -name '*.vcf' | sed "s/^/--variant /"}
        java -jar $GATK \
                -T GenotypeGVCFs \
                -R $REF \
                $datos \
                --disable_auto_index_creation_and_locking_when_reading_rods \
                -nt $NT \
                -o $target".build" \
        && mv $target".build" $target
