<config.mk


datos=`{find -L data/ -name '*.vcf' | sed "s/^/--variant /"}


results/Llamado-conjunto_raw.vcf:E:        $datos coord.bed
        set -x
        java -jar $GATK \
                -T GenotypeGVCFs \
                -R $REF \
                -L coord.bed \
                --variant $datos \
                --disable_auto_index_creation_and_locking_when_reading_rods \
                -nt $NT \
                -o $target".build" \
        && mv $target".build" $target
