< ../config.mk


#Recalibrating SNP

results/%_snp.recal:	data/%.vcf
        java -jar $GATK \
		-T VariantRecalibrator \
		-R $REF \
		-input "data/"$stem".vcf" \
		-mode SNP \
		-recalFile $target".build" \
		-tranchesFile "results/"$stem"_snp.tranches.build" \
		-rscriptFile "results/"$stem"-recalibrate_SNP_plots.R.build" \
		-nt $NT \
		-resource:hapmap,known=false,training=true,truth=true,prior=15.0 $HAPMAP \
		-resource:omni,known=false,training=true,truth=true,prior=12.0 $OMNI \
		-resource:1000G,known=true,training=true,truth=true,prior=10.0	$OTG \
		-resource:dbsnp,known=true,training=false,truth=false,prior=2.0 $dbSNP \
		-an DP -an QD -an FS -an SOR -an MQ \
                -an MQRankSum -an ReadPosRankSum \
	        && mv $target".build" $target \
		&& mv "results/"$stem"_snp.tranches.build" "results/"$stem"_snp.tranches" \
                && mv "results/"$stem"-recalibrate_SNP_plots.R.build" "results/"$stem"-recalibrate_SNP_plots.R" 


#Apply the recalibration in VCF file

results/%_snp_recaled.vcf:    results/%_snp.recal  data/%.vcf
        java -jar $GATK \
		-T ApplyRecalibration \
		-R $REF \
		-input "data/"$stem".vcf" \
		-mode SNP \
		-recalFile "results/"$stem"_snp.recal" \
		-nt $NT \
		-tranchesFile "results/"$stem"_snp.tranches" \
		-o $target".build" \
		-ts_filter_level 99.0 \
                && mv $target".build" $target 


#Recalibrating INDEL

results/%_indel.recal:        results/%_snp_recaled.vcf
	java -jar $GATK \
		-T VariantRecalibrator \
		-R $REF \
		-input "results/"$stem"_snp_recaled.vcf" \
		-mode INDEL \
		-recalFile $target".build" \
                -tranchesFile "results/"$stem"_indel.tranches.build" \
                -rscriptFile "results/"$stem"-recalibrate_INDEL_plots.R.build" \
		-nt $NT \
		-resource:mills,known=false,training=true,truth=true,prior=12.0 $INDELs \
		-an DP \
		-an QD \
		-an FS \
		-an SOR \
		-an MQRankSum \
		-an ReadPosRankSum \
		-an InbreedingCoeff \
                && mv $target".build" $target \
                && mv "results/"$stem"_indel.tranches.build" "results/"$stem"_indel.tranches" \
                && mv "results/"$stem"-recalibrate_INDEL_plots.R.build" "results/"$stem"-recalibrate_INDEL_plots.R"

#Apply recalibration in INDELS
results/%_snp_indel_recaled.vcf:       results/%_indel.recal results/%_snp_recaled.vcf
        java -jar $GATK \
		-T ApplyRecalibration \
		-R $REF \
		-input "results/"$stem"_snp_recaled.vcf"\
		-mode INDEL \
		-recalFile "results/"$stem"_indel.recal" \
		-nt $NT \
		-tranchesFile "results/"$stem"_indel.tranches" \
		-o $target".build" \
		-ts_filter_level 99.0 \
		&& mv $target".build" $target
