<config.mk

prueba1:VE:
	./targets | xargs mk

results/%.vcf:E:	data/%.recal2.bam coord.bed
	set -x
	java -jar $GATK \
		-T HaplotypeCaller \
		-R $REF \
		-L coord.bed \
		-I data/%.recal2.bam \
		--minPruning 3 \
		--emitRefConfidence GVCF \
                --variant_index_type LINEAR \
                --variant_index_parameter 128000 \
                -nct $NT \
		-o $target".build" \
	&& mv $target".build.bai" $target".bai"
