< config.mk

results/%.vcf.gz: data/%.vcf
	set -x
	mkdir -p `dirname $target`
	bgzip -c -@ $COMPRESSION_THREADS $prereq > $target.build \
	&& tabix -p vcf $target.build \
	&& mv $target.build $target \
	&& mv $target.build.tbi $target.tbi

